---
version: "3.9"

networks:
  db:

services:
  wikijs:
    image: requarks/wiki:2.5
    depends_on:
      - mariadb
    environment:
      #PUID: $app_pgid
      #PGID: $app_pgid
      TZ: $app_tz

      DB_TYPE: mariadb # $app_db_type #optional
      DB_HOST: mariadb # $app_db_host #optional
      DB_PORT: $app_db_port #optional
      DB_USER: $app_db_user #optional
      DB_PASS: $app_db_passwd #optional
      DB_NAME: $app_db_name #optional
      # Future: DB_PASS_FILE
      
      # Swarm only:
      # HA_ACTIVE: 1

        #volumes:
        #  - $app_dir_conf:/config
        #  - $app_dir_data:/data
    networks:
      db:

  mariadb:
    image: mariadb:10.6
    volumes:
      - $app_dir_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$app_db_name
      - MYSQL_USER=$app_db_user
      - MYSQL_PASSWORD=$app_db_passwd
      - MYSQL_ROOT_PASSWORD=$app_admin_passwd
        #- MYSQL_RANDOM_ROOT_PASSWORD=1

        #environment:
        #  MYSQL_ROOT_PASSWORD: "${app_admin_passwd}"
        #    # MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: yes
        #  MYSQL_DATABASE: "${app_db_name}"
        #  MYSQL_USER: "${app_db_user}"
        #  MYSQL_PASSWORD: "${app_db_passwd}"

    networks:
      db:


        #  mysql:
        #    image: mysql:8
        #    volumes:
        #      - $app_dir_db_data:/var/lib/mysql
        #    environment:
        #      MYSQL_ROOT_PASSWORD: "${app_admin_passwd}"
        #        # MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: yes
        #      MYSQL_DATABASE: "${app_db_name}"
        #      MYSQL_USER: "${app_db_user}"
        #      MYSQL_PASSWORD: "${app_db_passwd}"
        #
        #    networks:
        #      db:

