version: '3.7'

networks:
  proxy:
    #external: true
  internal:
    external: false
  services:
    external: true

services:
  
  formio:
    image: tiredofit/formio-api
    container_name: formio
    volumes:
      - $app_dir_conf/templates:/app/templates
    environment:
    - VIRTUAL_HOST=$app_fqdn
    - VIRTUAL_NETWORK=proxy
    - VIRTUAL_PORT=3001

    - DB_HOST=mongo

    - ROOT_EMAIL=admin@example.com
    - ROOT_PASS=password

    - DEBUG_MODE=FALSE
    - PROJECT_TEMPLATE=default
    networks:
    - proxy
    - internal
    - services
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    volumes:
    - ./db:/data/db
    command: mongod --smallfiles
    environment:
    - CONTAINER_NAME=mongo
    networks:
    - internal
    - services
    restart: unless-stopped 

  mongo-backup:
    image: tiredofit/db-backup
    container_name: mongo-backup
    links:
    - mongo
    volumes:
    - ./dbbackup:/backups
    environment:
    - DB_TYPE=mongo
    - DB_HOST=mongo
    - DB_DUMP_FREQ=1440
    - DB_DUMP_BEGIN=0000
    - DB_CLEANUP_TIME=8640
    - MD5=TRUE
    - COMPRESSION=GZ
    networks:
    - internal
    - services
    restart: always


