version: '3'

networks:
  db:

services:

  front:
    image: vikunja/frontend
      #labels:
      #  - "traefik.enable=true"
      #  - "traefik.http.routers.vikunja-frontend.rule=Host(`vikunja.example.com`)"
      #  - "traefik.http.routers.vikunja-frontend.entrypoints=https"
      #  - "traefik.http.routers.vikunja-frontend.tls.certResolver=acme"
    networks:
      - db
    restart: unless-stopped

  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: $app_db_pass
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: $app_db_user
      VIKUNJA_DATABASE_DATABASE: $app_db_name
      VIKUNJA_SERVICE_JWTSECRET: $app_token
      VIKUNJA_SERVICE_FRONTENDURL: $app_prot://$app_fqdn
    volumes: 
      - $app_dir_data:/app/vikunja/files
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
      #    labels:
      #      - "traefik.enable=true"
      #      - "traefik.http.routers.vikunja-api.rule=Host(`vikunja.example.com`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
      #      - "traefik.http.routers.vikunja-api.entrypoints=https"
      #      - "traefik.http.routers.vikunja-api.tls.certResolver=acme"
      

  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: $app_db_admin_pass 
      MYSQL_USER: $app_db_user
      MYSQL_PASSWORD: $app_db_pass
      MYSQL_DATABASE: $app_db_name
    volumes:
      - $app_dir_db_data:/var/lib/mysql
    restart: unless-stopped
    command: --max-connections=1000
    networks:
      - db

