version: '3.3'

networks:
  db:
services:
  homechart:
    depends_on:
      - postgres
    environment:
      # HOMECHART_APP_ADMINEMAILADDRESSES
      HOMECHART_APP_BASEURL: $app_prot://$app_fqdn



      HOMECHART_POSTGRESQL_HOSTNAME: postgres
      HOMECHART_POSTGRESQL_PASSWORD: $app_db_passwd
      HOMECHART_POSTGRESQL_USERNAME: postgres
    image: candiddev/homechart:latest
      #ports:
      #  - "3000:3000"
    restart: always
    networks:
      db:

  postgres:
    environment:
      POSTGRES_PASSWORD: $app_db_passwd
    image: postgres:14
    restart: always
    volumes:
      - $app_dir_db_data:/var/lib/postgresql/data
    networks:
      db:


