version: '3.7'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$app_tz
    volumes:
      - $app_dir_conf:/config


