---
version: "3.9"

services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      TZ: $app_tz
      LOG_LEVEL: ${app_log_level:-info}
      LOG_HTML: ${flaresolverr_log_html:-false}
      CAPTCHA_SOLVER: ${flaresolverr_captcha:-none}
